// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace LoadDWHNorthwind.Model.Models;

public partial class DWHNorthwindContext : DbContext
{
    public DWHNorthwindContext(DbContextOptions<DWHNorthwindContext> options)
        : base(options)
    {
    }

    public virtual DbSet<FactOrdenes> FactOrdenes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<FactOrdenes>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("FactOrdenes", "DWH");

            entity.Property(e => e.CiudadID).HasMaxLength(15);
            entity.Property(e => e.ClienteID)
                .HasMaxLength(5)
                .IsFixedLength();
            entity.Property(e => e.Fecha).HasColumnType("datetime");
            entity.Property(e => e.PaisID).HasMaxLength(15);
            entity.Property(e => e.RegionID).HasMaxLength(15);
            entity.Property(e => e.TotalVentas).HasColumnType("money");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}