// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace LoadDWHNorthwind.Model.Models;

public partial class DWHNorthwindContext : DbContext
{
    public DWHNorthwindContext(DbContextOptions<DWHNorthwindContext> options)
        : base(options)
    {
    }

    public virtual DbSet<FactOrdenes> FactOrdenes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<FactOrdenes>(entity =>
        {
            entity.HasKey(e => e.FactOrdenesKey);

            entity.ToTable("FactOrdenes", "DHW");

            entity.HasIndex(e => new { e.FactOrdenesKey, e.OrdenID }, "idx_orderid");

            entity.Property(e => e.Ciudad).HasMaxLength(20);
            entity.Property(e => e.Pais).HasMaxLength(20);
            entity.Property(e => e.Precio).HasColumnType("money");
            entity.Property(e => e.Region).HasMaxLength(20);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}