// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadDWHNorthwind.Model.Models;

public partial class FactOrdenes
{
    public int OrdenID { get; set; }

    public string ClienteID { get; set; }

    public int ProductoID { get; set; }

    public int? EmpleadoID { get; set; }

    public DateTime? Fecha { get; set; }

    public int? CargadorID { get; set; }

    public string CiudadID { get; set; }

    public string PaisID { get; set; }

    public string RegionID { get; set; }

    public decimal? TotalVentas { get; set; }

    public int? Cantidad { get; set; }
}